FROM golang:1.18.8-alpine3.16 AS builder

WORKDIR /app
COPY . .
RUN go mod download
RUN go build -ldflags "-s -w" -o bin/frontend ./frontend

FROM alpine:latest as runner

WORKDIR /
COPY --from=builder /app/bin/frontend /frontend
EXPOSE 8080

ENTRYPOINT [ "/frontend" ]

