FROM golang:1.18.8-alpine3.16 AS builder

WORKDIR /app
COPY . .
RUN go mod download
RUN go build -ldflags "-s -w" -o bin/backend ./backend

FROM alpine:latest as runner

WORKDIR /
COPY --from=builder /app/bin/backend /backend
EXPOSE 9090

ENTRYPOINT [ "/backend" ]

